<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>PersistentWindows.SystrayShell</RootNamespace>
    <AssemblyName>PersistentWindows</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Resources\pwIcon.ico</ApplicationIcon>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="HotKey.cs" />
    <Compile Include="SplashForm.cs" />
    <Compile Include="SplashForm.Designer.cs" />
    <Compile Include="SystrayForm.cs" />
    <Compile Include="SystrayForm.Designer.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Properties\Resources.Designer.cs" />
    <Compile Include="Properties\Settings.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Properties\Resources.resx" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PersistentWindows.Common">
      <HintPath>D:\PersistentWindows\PersistentWindows.Common.dll</HintPath>
    </Reference>
    <Reference Include="LiteDB">
      <HintPath>D:\PersistentWindows\LiteDB.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
